/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardPharmacistRouteImport } from './routes/dashboard/pharmacist'
import { Route as DashboardPatientRouteImport } from './routes/dashboard/patient'
import { Route as DashboardDoctorRouteImport } from './routes/dashboard/doctor'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'
import { Route as DashboardPharmacistIndexRouteImport } from './routes/dashboard/pharmacist/index'
import { Route as DashboardPatientIndexRouteImport } from './routes/dashboard/patient/index'
import { Route as DashboardDoctorIndexRouteImport } from './routes/dashboard/doctor/index'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard/admin/index'
import { Route as DashboardPharmacistSettingsRouteImport } from './routes/dashboard/pharmacist/settings'
import { Route as DashboardPharmacistProfileRouteImport } from './routes/dashboard/pharmacist/profile'
import { Route as DashboardPharmacistOrdersRouteImport } from './routes/dashboard/pharmacist/orders'
import { Route as DashboardPharmacistMedicineRouteImport } from './routes/dashboard/pharmacist/medicine'
import { Route as DashboardPharmacistInventoryRouteImport } from './routes/dashboard/pharmacist/inventory'
import { Route as DashboardPatientSettingsRouteImport } from './routes/dashboard/patient/settings'
import { Route as DashboardPatientProfileRouteImport } from './routes/dashboard/patient/profile'
import { Route as DashboardPatientPrescriptionsRouteImport } from './routes/dashboard/patient/prescriptions'
import { Route as DashboardPatientOrdersRouteImport } from './routes/dashboard/patient/orders'
import { Route as DashboardPatientBookAppointmentRouteImport } from './routes/dashboard/patient/book-appointment'
import { Route as DashboardPatientAppointmentsRouteImport } from './routes/dashboard/patient/appointments'
import { Route as DashboardDoctorSettingsRouteImport } from './routes/dashboard/doctor/settings'
import { Route as DashboardDoctorProfileRouteImport } from './routes/dashboard/doctor/profile'
import { Route as DashboardDoctorPrescriptionsRouteImport } from './routes/dashboard/doctor/prescriptions'
import { Route as DashboardDoctorAvailabilityRouteImport } from './routes/dashboard/doctor/availability'
import { Route as DashboardDoctorAppointmentsRouteImport } from './routes/dashboard/doctor/appointments'
import { Route as DashboardAdminUsersRouteImport } from './routes/dashboard/admin/users'
import { Route as DashboardAdminSettingsRouteImport } from './routes/dashboard/admin/settings'
import { Route as DashboardPharmacistProfileIndexRouteImport } from './routes/dashboard/pharmacist/profile/index'
import { Route as DashboardPharmacistOrdersIndexRouteImport } from './routes/dashboard/pharmacist/orders/index'
import { Route as DashboardPatientProfileIndexRouteImport } from './routes/dashboard/patient/profile/index'
import { Route as DashboardPatientPrescriptionsIndexRouteImport } from './routes/dashboard/patient/prescriptions/index'
import { Route as DashboardPatientOrdersIndexRouteImport } from './routes/dashboard/patient/orders/index'
import { Route as DashboardDoctorProfileIndexRouteImport } from './routes/dashboard/doctor/profile/index'
import { Route as DashboardDoctorPrescriptionsIndexRouteImport } from './routes/dashboard/doctor/prescriptions/index'
import { Route as DashboardDoctorAppointmentsIndexRouteImport } from './routes/dashboard/doctor/appointments/index'
import { Route as DashboardPharmacistProfileEditRouteImport } from './routes/dashboard/pharmacist/profile/edit'
import { Route as DashboardPharmacistProfileCreateRouteImport } from './routes/dashboard/pharmacist/profile/create'
import { Route as DashboardPharmacistOrdersOrderIdRouteImport } from './routes/dashboard/pharmacist/orders/$orderId'
import { Route as DashboardPatientProfileEditRouteImport } from './routes/dashboard/patient/profile/edit'
import { Route as DashboardPatientProfileCreateRouteImport } from './routes/dashboard/patient/profile/create'
import { Route as DashboardPatientPrescriptionsPrescriptionIdRouteImport } from './routes/dashboard/patient/prescriptions/$prescriptionId'
import { Route as DashboardPatientOrdersNewRouteImport } from './routes/dashboard/patient/orders/new'
import { Route as DashboardPatientOrdersOrderIdRouteImport } from './routes/dashboard/patient/orders/$orderId'
import { Route as DashboardDoctorProfileEditRouteImport } from './routes/dashboard/doctor/profile/edit'
import { Route as DashboardDoctorProfileCreateRouteImport } from './routes/dashboard/doctor/profile/create'
import { Route as DashboardDoctorPrescriptionsNewRouteImport } from './routes/dashboard/doctor/prescriptions/new'
import { Route as DashboardDoctorPrescriptionsPrescriptionIdRouteImport } from './routes/dashboard/doctor/prescriptions/$prescriptionId'
import { Route as DashboardDoctorAppointmentsAppointmentIdRouteImport } from './routes/dashboard/doctor/appointments/$appointmentId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPharmacistRoute = DashboardPharmacistRouteImport.update({
  id: '/pharmacist',
  path: '/pharmacist',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPatientRoute = DashboardPatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDoctorRoute = DashboardDoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPharmacistIndexRoute =
  DashboardPharmacistIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardPharmacistRoute,
  } as any)
const DashboardPatientIndexRoute = DashboardPatientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardPatientRoute,
} as any)
const DashboardDoctorIndexRoute = DashboardDoctorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardDoctorRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardPharmacistSettingsRoute =
  DashboardPharmacistSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardPharmacistRoute,
  } as any)
const DashboardPharmacistProfileRoute =
  DashboardPharmacistProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => DashboardPharmacistRoute,
  } as any)
const DashboardPharmacistOrdersRoute =
  DashboardPharmacistOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => DashboardPharmacistRoute,
  } as any)
const DashboardPharmacistMedicineRoute =
  DashboardPharmacistMedicineRouteImport.update({
    id: '/medicine',
    path: '/medicine',
    getParentRoute: () => DashboardPharmacistRoute,
  } as any)
const DashboardPharmacistInventoryRoute =
  DashboardPharmacistInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => DashboardPharmacistRoute,
  } as any)
const DashboardPatientSettingsRoute =
  DashboardPatientSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardPatientRoute,
  } as any)
const DashboardPatientProfileRoute = DashboardPatientProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardPatientRoute,
} as any)
const DashboardPatientPrescriptionsRoute =
  DashboardPatientPrescriptionsRouteImport.update({
    id: '/prescriptions',
    path: '/prescriptions',
    getParentRoute: () => DashboardPatientRoute,
  } as any)
const DashboardPatientOrdersRoute = DashboardPatientOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardPatientRoute,
} as any)
const DashboardPatientBookAppointmentRoute =
  DashboardPatientBookAppointmentRouteImport.update({
    id: '/book-appointment',
    path: '/book-appointment',
    getParentRoute: () => DashboardPatientRoute,
  } as any)
const DashboardPatientAppointmentsRoute =
  DashboardPatientAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => DashboardPatientRoute,
  } as any)
const DashboardDoctorSettingsRoute = DashboardDoctorSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardDoctorRoute,
} as any)
const DashboardDoctorProfileRoute = DashboardDoctorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardDoctorRoute,
} as any)
const DashboardDoctorPrescriptionsRoute =
  DashboardDoctorPrescriptionsRouteImport.update({
    id: '/prescriptions',
    path: '/prescriptions',
    getParentRoute: () => DashboardDoctorRoute,
  } as any)
const DashboardDoctorAvailabilityRoute =
  DashboardDoctorAvailabilityRouteImport.update({
    id: '/availability',
    path: '/availability',
    getParentRoute: () => DashboardDoctorRoute,
  } as any)
const DashboardDoctorAppointmentsRoute =
  DashboardDoctorAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => DashboardDoctorRoute,
  } as any)
const DashboardAdminUsersRoute = DashboardAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminSettingsRoute = DashboardAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardPharmacistProfileIndexRoute =
  DashboardPharmacistProfileIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardPharmacistProfileRoute,
  } as any)
const DashboardPharmacistOrdersIndexRoute =
  DashboardPharmacistOrdersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardPharmacistOrdersRoute,
  } as any)
const DashboardPatientProfileIndexRoute =
  DashboardPatientProfileIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardPatientProfileRoute,
  } as any)
const DashboardPatientPrescriptionsIndexRoute =
  DashboardPatientPrescriptionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardPatientPrescriptionsRoute,
  } as any)
const DashboardPatientOrdersIndexRoute =
  DashboardPatientOrdersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardPatientOrdersRoute,
  } as any)
const DashboardDoctorProfileIndexRoute =
  DashboardDoctorProfileIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardDoctorProfileRoute,
  } as any)
const DashboardDoctorPrescriptionsIndexRoute =
  DashboardDoctorPrescriptionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardDoctorPrescriptionsRoute,
  } as any)
const DashboardDoctorAppointmentsIndexRoute =
  DashboardDoctorAppointmentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardDoctorAppointmentsRoute,
  } as any)
const DashboardPharmacistProfileEditRoute =
  DashboardPharmacistProfileEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => DashboardPharmacistProfileRoute,
  } as any)
const DashboardPharmacistProfileCreateRoute =
  DashboardPharmacistProfileCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => DashboardPharmacistProfileRoute,
  } as any)
const DashboardPharmacistOrdersOrderIdRoute =
  DashboardPharmacistOrdersOrderIdRouteImport.update({
    id: '/$orderId',
    path: '/$orderId',
    getParentRoute: () => DashboardPharmacistOrdersRoute,
  } as any)
const DashboardPatientProfileEditRoute =
  DashboardPatientProfileEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => DashboardPatientProfileRoute,
  } as any)
const DashboardPatientProfileCreateRoute =
  DashboardPatientProfileCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => DashboardPatientProfileRoute,
  } as any)
const DashboardPatientPrescriptionsPrescriptionIdRoute =
  DashboardPatientPrescriptionsPrescriptionIdRouteImport.update({
    id: '/$prescriptionId',
    path: '/$prescriptionId',
    getParentRoute: () => DashboardPatientPrescriptionsRoute,
  } as any)
const DashboardPatientOrdersNewRoute =
  DashboardPatientOrdersNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => DashboardPatientOrdersRoute,
  } as any)
const DashboardPatientOrdersOrderIdRoute =
  DashboardPatientOrdersOrderIdRouteImport.update({
    id: '/$orderId',
    path: '/$orderId',
    getParentRoute: () => DashboardPatientOrdersRoute,
  } as any)
const DashboardDoctorProfileEditRoute =
  DashboardDoctorProfileEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => DashboardDoctorProfileRoute,
  } as any)
const DashboardDoctorProfileCreateRoute =
  DashboardDoctorProfileCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => DashboardDoctorProfileRoute,
  } as any)
const DashboardDoctorPrescriptionsNewRoute =
  DashboardDoctorPrescriptionsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => DashboardDoctorPrescriptionsRoute,
  } as any)
const DashboardDoctorPrescriptionsPrescriptionIdRoute =
  DashboardDoctorPrescriptionsPrescriptionIdRouteImport.update({
    id: '/$prescriptionId',
    path: '/$prescriptionId',
    getParentRoute: () => DashboardDoctorPrescriptionsRoute,
  } as any)
const DashboardDoctorAppointmentsAppointmentIdRoute =
  DashboardDoctorAppointmentsAppointmentIdRouteImport.update({
    id: '/$appointmentId',
    path: '/$appointmentId',
    getParentRoute: () => DashboardDoctorAppointmentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/doctor': typeof DashboardDoctorRouteWithChildren
  '/dashboard/patient': typeof DashboardPatientRouteWithChildren
  '/dashboard/pharmacist': typeof DashboardPharmacistRouteWithChildren
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/doctor/appointments': typeof DashboardDoctorAppointmentsRouteWithChildren
  '/dashboard/doctor/availability': typeof DashboardDoctorAvailabilityRoute
  '/dashboard/doctor/prescriptions': typeof DashboardDoctorPrescriptionsRouteWithChildren
  '/dashboard/doctor/profile': typeof DashboardDoctorProfileRouteWithChildren
  '/dashboard/doctor/settings': typeof DashboardDoctorSettingsRoute
  '/dashboard/patient/appointments': typeof DashboardPatientAppointmentsRoute
  '/dashboard/patient/book-appointment': typeof DashboardPatientBookAppointmentRoute
  '/dashboard/patient/orders': typeof DashboardPatientOrdersRouteWithChildren
  '/dashboard/patient/prescriptions': typeof DashboardPatientPrescriptionsRouteWithChildren
  '/dashboard/patient/profile': typeof DashboardPatientProfileRouteWithChildren
  '/dashboard/patient/settings': typeof DashboardPatientSettingsRoute
  '/dashboard/pharmacist/inventory': typeof DashboardPharmacistInventoryRoute
  '/dashboard/pharmacist/medicine': typeof DashboardPharmacistMedicineRoute
  '/dashboard/pharmacist/orders': typeof DashboardPharmacistOrdersRouteWithChildren
  '/dashboard/pharmacist/profile': typeof DashboardPharmacistProfileRouteWithChildren
  '/dashboard/pharmacist/settings': typeof DashboardPharmacistSettingsRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/doctor/': typeof DashboardDoctorIndexRoute
  '/dashboard/patient/': typeof DashboardPatientIndexRoute
  '/dashboard/pharmacist/': typeof DashboardPharmacistIndexRoute
  '/dashboard/doctor/appointments/$appointmentId': typeof DashboardDoctorAppointmentsAppointmentIdRoute
  '/dashboard/doctor/prescriptions/$prescriptionId': typeof DashboardDoctorPrescriptionsPrescriptionIdRoute
  '/dashboard/doctor/prescriptions/new': typeof DashboardDoctorPrescriptionsNewRoute
  '/dashboard/doctor/profile/create': typeof DashboardDoctorProfileCreateRoute
  '/dashboard/doctor/profile/edit': typeof DashboardDoctorProfileEditRoute
  '/dashboard/patient/orders/$orderId': typeof DashboardPatientOrdersOrderIdRoute
  '/dashboard/patient/orders/new': typeof DashboardPatientOrdersNewRoute
  '/dashboard/patient/prescriptions/$prescriptionId': typeof DashboardPatientPrescriptionsPrescriptionIdRoute
  '/dashboard/patient/profile/create': typeof DashboardPatientProfileCreateRoute
  '/dashboard/patient/profile/edit': typeof DashboardPatientProfileEditRoute
  '/dashboard/pharmacist/orders/$orderId': typeof DashboardPharmacistOrdersOrderIdRoute
  '/dashboard/pharmacist/profile/create': typeof DashboardPharmacistProfileCreateRoute
  '/dashboard/pharmacist/profile/edit': typeof DashboardPharmacistProfileEditRoute
  '/dashboard/doctor/appointments/': typeof DashboardDoctorAppointmentsIndexRoute
  '/dashboard/doctor/prescriptions/': typeof DashboardDoctorPrescriptionsIndexRoute
  '/dashboard/doctor/profile/': typeof DashboardDoctorProfileIndexRoute
  '/dashboard/patient/orders/': typeof DashboardPatientOrdersIndexRoute
  '/dashboard/patient/prescriptions/': typeof DashboardPatientPrescriptionsIndexRoute
  '/dashboard/patient/profile/': typeof DashboardPatientProfileIndexRoute
  '/dashboard/pharmacist/orders/': typeof DashboardPharmacistOrdersIndexRoute
  '/dashboard/pharmacist/profile/': typeof DashboardPharmacistProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/doctor/availability': typeof DashboardDoctorAvailabilityRoute
  '/dashboard/doctor/settings': typeof DashboardDoctorSettingsRoute
  '/dashboard/patient/appointments': typeof DashboardPatientAppointmentsRoute
  '/dashboard/patient/book-appointment': typeof DashboardPatientBookAppointmentRoute
  '/dashboard/patient/settings': typeof DashboardPatientSettingsRoute
  '/dashboard/pharmacist/inventory': typeof DashboardPharmacistInventoryRoute
  '/dashboard/pharmacist/medicine': typeof DashboardPharmacistMedicineRoute
  '/dashboard/pharmacist/settings': typeof DashboardPharmacistSettingsRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/doctor': typeof DashboardDoctorIndexRoute
  '/dashboard/patient': typeof DashboardPatientIndexRoute
  '/dashboard/pharmacist': typeof DashboardPharmacistIndexRoute
  '/dashboard/doctor/appointments/$appointmentId': typeof DashboardDoctorAppointmentsAppointmentIdRoute
  '/dashboard/doctor/prescriptions/$prescriptionId': typeof DashboardDoctorPrescriptionsPrescriptionIdRoute
  '/dashboard/doctor/prescriptions/new': typeof DashboardDoctorPrescriptionsNewRoute
  '/dashboard/doctor/profile/create': typeof DashboardDoctorProfileCreateRoute
  '/dashboard/doctor/profile/edit': typeof DashboardDoctorProfileEditRoute
  '/dashboard/patient/orders/$orderId': typeof DashboardPatientOrdersOrderIdRoute
  '/dashboard/patient/orders/new': typeof DashboardPatientOrdersNewRoute
  '/dashboard/patient/prescriptions/$prescriptionId': typeof DashboardPatientPrescriptionsPrescriptionIdRoute
  '/dashboard/patient/profile/create': typeof DashboardPatientProfileCreateRoute
  '/dashboard/patient/profile/edit': typeof DashboardPatientProfileEditRoute
  '/dashboard/pharmacist/orders/$orderId': typeof DashboardPharmacistOrdersOrderIdRoute
  '/dashboard/pharmacist/profile/create': typeof DashboardPharmacistProfileCreateRoute
  '/dashboard/pharmacist/profile/edit': typeof DashboardPharmacistProfileEditRoute
  '/dashboard/doctor/appointments': typeof DashboardDoctorAppointmentsIndexRoute
  '/dashboard/doctor/prescriptions': typeof DashboardDoctorPrescriptionsIndexRoute
  '/dashboard/doctor/profile': typeof DashboardDoctorProfileIndexRoute
  '/dashboard/patient/orders': typeof DashboardPatientOrdersIndexRoute
  '/dashboard/patient/prescriptions': typeof DashboardPatientPrescriptionsIndexRoute
  '/dashboard/patient/profile': typeof DashboardPatientProfileIndexRoute
  '/dashboard/pharmacist/orders': typeof DashboardPharmacistOrdersIndexRoute
  '/dashboard/pharmacist/profile': typeof DashboardPharmacistProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/doctor': typeof DashboardDoctorRouteWithChildren
  '/dashboard/patient': typeof DashboardPatientRouteWithChildren
  '/dashboard/pharmacist': typeof DashboardPharmacistRouteWithChildren
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/doctor/appointments': typeof DashboardDoctorAppointmentsRouteWithChildren
  '/dashboard/doctor/availability': typeof DashboardDoctorAvailabilityRoute
  '/dashboard/doctor/prescriptions': typeof DashboardDoctorPrescriptionsRouteWithChildren
  '/dashboard/doctor/profile': typeof DashboardDoctorProfileRouteWithChildren
  '/dashboard/doctor/settings': typeof DashboardDoctorSettingsRoute
  '/dashboard/patient/appointments': typeof DashboardPatientAppointmentsRoute
  '/dashboard/patient/book-appointment': typeof DashboardPatientBookAppointmentRoute
  '/dashboard/patient/orders': typeof DashboardPatientOrdersRouteWithChildren
  '/dashboard/patient/prescriptions': typeof DashboardPatientPrescriptionsRouteWithChildren
  '/dashboard/patient/profile': typeof DashboardPatientProfileRouteWithChildren
  '/dashboard/patient/settings': typeof DashboardPatientSettingsRoute
  '/dashboard/pharmacist/inventory': typeof DashboardPharmacistInventoryRoute
  '/dashboard/pharmacist/medicine': typeof DashboardPharmacistMedicineRoute
  '/dashboard/pharmacist/orders': typeof DashboardPharmacistOrdersRouteWithChildren
  '/dashboard/pharmacist/profile': typeof DashboardPharmacistProfileRouteWithChildren
  '/dashboard/pharmacist/settings': typeof DashboardPharmacistSettingsRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/doctor/': typeof DashboardDoctorIndexRoute
  '/dashboard/patient/': typeof DashboardPatientIndexRoute
  '/dashboard/pharmacist/': typeof DashboardPharmacistIndexRoute
  '/dashboard/doctor/appointments/$appointmentId': typeof DashboardDoctorAppointmentsAppointmentIdRoute
  '/dashboard/doctor/prescriptions/$prescriptionId': typeof DashboardDoctorPrescriptionsPrescriptionIdRoute
  '/dashboard/doctor/prescriptions/new': typeof DashboardDoctorPrescriptionsNewRoute
  '/dashboard/doctor/profile/create': typeof DashboardDoctorProfileCreateRoute
  '/dashboard/doctor/profile/edit': typeof DashboardDoctorProfileEditRoute
  '/dashboard/patient/orders/$orderId': typeof DashboardPatientOrdersOrderIdRoute
  '/dashboard/patient/orders/new': typeof DashboardPatientOrdersNewRoute
  '/dashboard/patient/prescriptions/$prescriptionId': typeof DashboardPatientPrescriptionsPrescriptionIdRoute
  '/dashboard/patient/profile/create': typeof DashboardPatientProfileCreateRoute
  '/dashboard/patient/profile/edit': typeof DashboardPatientProfileEditRoute
  '/dashboard/pharmacist/orders/$orderId': typeof DashboardPharmacistOrdersOrderIdRoute
  '/dashboard/pharmacist/profile/create': typeof DashboardPharmacistProfileCreateRoute
  '/dashboard/pharmacist/profile/edit': typeof DashboardPharmacistProfileEditRoute
  '/dashboard/doctor/appointments/': typeof DashboardDoctorAppointmentsIndexRoute
  '/dashboard/doctor/prescriptions/': typeof DashboardDoctorPrescriptionsIndexRoute
  '/dashboard/doctor/profile/': typeof DashboardDoctorProfileIndexRoute
  '/dashboard/patient/orders/': typeof DashboardPatientOrdersIndexRoute
  '/dashboard/patient/prescriptions/': typeof DashboardPatientPrescriptionsIndexRoute
  '/dashboard/patient/profile/': typeof DashboardPatientProfileIndexRoute
  '/dashboard/pharmacist/orders/': typeof DashboardPharmacistOrdersIndexRoute
  '/dashboard/pharmacist/profile/': typeof DashboardPharmacistProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/admin'
    | '/dashboard/doctor'
    | '/dashboard/patient'
    | '/dashboard/pharmacist'
    | '/dashboard/admin/settings'
    | '/dashboard/admin/users'
    | '/dashboard/doctor/appointments'
    | '/dashboard/doctor/availability'
    | '/dashboard/doctor/prescriptions'
    | '/dashboard/doctor/profile'
    | '/dashboard/doctor/settings'
    | '/dashboard/patient/appointments'
    | '/dashboard/patient/book-appointment'
    | '/dashboard/patient/orders'
    | '/dashboard/patient/prescriptions'
    | '/dashboard/patient/profile'
    | '/dashboard/patient/settings'
    | '/dashboard/pharmacist/inventory'
    | '/dashboard/pharmacist/medicine'
    | '/dashboard/pharmacist/orders'
    | '/dashboard/pharmacist/profile'
    | '/dashboard/pharmacist/settings'
    | '/dashboard/admin/'
    | '/dashboard/doctor/'
    | '/dashboard/patient/'
    | '/dashboard/pharmacist/'
    | '/dashboard/doctor/appointments/$appointmentId'
    | '/dashboard/doctor/prescriptions/$prescriptionId'
    | '/dashboard/doctor/prescriptions/new'
    | '/dashboard/doctor/profile/create'
    | '/dashboard/doctor/profile/edit'
    | '/dashboard/patient/orders/$orderId'
    | '/dashboard/patient/orders/new'
    | '/dashboard/patient/prescriptions/$prescriptionId'
    | '/dashboard/patient/profile/create'
    | '/dashboard/patient/profile/edit'
    | '/dashboard/pharmacist/orders/$orderId'
    | '/dashboard/pharmacist/profile/create'
    | '/dashboard/pharmacist/profile/edit'
    | '/dashboard/doctor/appointments/'
    | '/dashboard/doctor/prescriptions/'
    | '/dashboard/doctor/profile/'
    | '/dashboard/patient/orders/'
    | '/dashboard/patient/prescriptions/'
    | '/dashboard/patient/profile/'
    | '/dashboard/pharmacist/orders/'
    | '/dashboard/pharmacist/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/admin/settings'
    | '/dashboard/admin/users'
    | '/dashboard/doctor/availability'
    | '/dashboard/doctor/settings'
    | '/dashboard/patient/appointments'
    | '/dashboard/patient/book-appointment'
    | '/dashboard/patient/settings'
    | '/dashboard/pharmacist/inventory'
    | '/dashboard/pharmacist/medicine'
    | '/dashboard/pharmacist/settings'
    | '/dashboard/admin'
    | '/dashboard/doctor'
    | '/dashboard/patient'
    | '/dashboard/pharmacist'
    | '/dashboard/doctor/appointments/$appointmentId'
    | '/dashboard/doctor/prescriptions/$prescriptionId'
    | '/dashboard/doctor/prescriptions/new'
    | '/dashboard/doctor/profile/create'
    | '/dashboard/doctor/profile/edit'
    | '/dashboard/patient/orders/$orderId'
    | '/dashboard/patient/orders/new'
    | '/dashboard/patient/prescriptions/$prescriptionId'
    | '/dashboard/patient/profile/create'
    | '/dashboard/patient/profile/edit'
    | '/dashboard/pharmacist/orders/$orderId'
    | '/dashboard/pharmacist/profile/create'
    | '/dashboard/pharmacist/profile/edit'
    | '/dashboard/doctor/appointments'
    | '/dashboard/doctor/prescriptions'
    | '/dashboard/doctor/profile'
    | '/dashboard/patient/orders'
    | '/dashboard/patient/prescriptions'
    | '/dashboard/patient/profile'
    | '/dashboard/pharmacist/orders'
    | '/dashboard/pharmacist/profile'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/admin'
    | '/dashboard/doctor'
    | '/dashboard/patient'
    | '/dashboard/pharmacist'
    | '/dashboard/admin/settings'
    | '/dashboard/admin/users'
    | '/dashboard/doctor/appointments'
    | '/dashboard/doctor/availability'
    | '/dashboard/doctor/prescriptions'
    | '/dashboard/doctor/profile'
    | '/dashboard/doctor/settings'
    | '/dashboard/patient/appointments'
    | '/dashboard/patient/book-appointment'
    | '/dashboard/patient/orders'
    | '/dashboard/patient/prescriptions'
    | '/dashboard/patient/profile'
    | '/dashboard/patient/settings'
    | '/dashboard/pharmacist/inventory'
    | '/dashboard/pharmacist/medicine'
    | '/dashboard/pharmacist/orders'
    | '/dashboard/pharmacist/profile'
    | '/dashboard/pharmacist/settings'
    | '/dashboard/admin/'
    | '/dashboard/doctor/'
    | '/dashboard/patient/'
    | '/dashboard/pharmacist/'
    | '/dashboard/doctor/appointments/$appointmentId'
    | '/dashboard/doctor/prescriptions/$prescriptionId'
    | '/dashboard/doctor/prescriptions/new'
    | '/dashboard/doctor/profile/create'
    | '/dashboard/doctor/profile/edit'
    | '/dashboard/patient/orders/$orderId'
    | '/dashboard/patient/orders/new'
    | '/dashboard/patient/prescriptions/$prescriptionId'
    | '/dashboard/patient/profile/create'
    | '/dashboard/patient/profile/edit'
    | '/dashboard/pharmacist/orders/$orderId'
    | '/dashboard/pharmacist/profile/create'
    | '/dashboard/pharmacist/profile/edit'
    | '/dashboard/doctor/appointments/'
    | '/dashboard/doctor/prescriptions/'
    | '/dashboard/doctor/profile/'
    | '/dashboard/patient/orders/'
    | '/dashboard/patient/prescriptions/'
    | '/dashboard/patient/profile/'
    | '/dashboard/pharmacist/orders/'
    | '/dashboard/pharmacist/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/pharmacist': {
      id: '/dashboard/pharmacist'
      path: '/pharmacist'
      fullPath: '/dashboard/pharmacist'
      preLoaderRoute: typeof DashboardPharmacistRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/patient': {
      id: '/dashboard/patient'
      path: '/patient'
      fullPath: '/dashboard/patient'
      preLoaderRoute: typeof DashboardPatientRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/doctor': {
      id: '/dashboard/doctor'
      path: '/doctor'
      fullPath: '/dashboard/doctor'
      preLoaderRoute: typeof DashboardDoctorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pharmacist/': {
      id: '/dashboard/pharmacist/'
      path: '/'
      fullPath: '/dashboard/pharmacist/'
      preLoaderRoute: typeof DashboardPharmacistIndexRouteImport
      parentRoute: typeof DashboardPharmacistRoute
    }
    '/dashboard/patient/': {
      id: '/dashboard/patient/'
      path: '/'
      fullPath: '/dashboard/patient/'
      preLoaderRoute: typeof DashboardPatientIndexRouteImport
      parentRoute: typeof DashboardPatientRoute
    }
    '/dashboard/doctor/': {
      id: '/dashboard/doctor/'
      path: '/'
      fullPath: '/dashboard/doctor/'
      preLoaderRoute: typeof DashboardDoctorIndexRouteImport
      parentRoute: typeof DashboardDoctorRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/pharmacist/settings': {
      id: '/dashboard/pharmacist/settings'
      path: '/settings'
      fullPath: '/dashboard/pharmacist/settings'
      preLoaderRoute: typeof DashboardPharmacistSettingsRouteImport
      parentRoute: typeof DashboardPharmacistRoute
    }
    '/dashboard/pharmacist/profile': {
      id: '/dashboard/pharmacist/profile'
      path: '/profile'
      fullPath: '/dashboard/pharmacist/profile'
      preLoaderRoute: typeof DashboardPharmacistProfileRouteImport
      parentRoute: typeof DashboardPharmacistRoute
    }
    '/dashboard/pharmacist/orders': {
      id: '/dashboard/pharmacist/orders'
      path: '/orders'
      fullPath: '/dashboard/pharmacist/orders'
      preLoaderRoute: typeof DashboardPharmacistOrdersRouteImport
      parentRoute: typeof DashboardPharmacistRoute
    }
    '/dashboard/pharmacist/medicine': {
      id: '/dashboard/pharmacist/medicine'
      path: '/medicine'
      fullPath: '/dashboard/pharmacist/medicine'
      preLoaderRoute: typeof DashboardPharmacistMedicineRouteImport
      parentRoute: typeof DashboardPharmacistRoute
    }
    '/dashboard/pharmacist/inventory': {
      id: '/dashboard/pharmacist/inventory'
      path: '/inventory'
      fullPath: '/dashboard/pharmacist/inventory'
      preLoaderRoute: typeof DashboardPharmacistInventoryRouteImport
      parentRoute: typeof DashboardPharmacistRoute
    }
    '/dashboard/patient/settings': {
      id: '/dashboard/patient/settings'
      path: '/settings'
      fullPath: '/dashboard/patient/settings'
      preLoaderRoute: typeof DashboardPatientSettingsRouteImport
      parentRoute: typeof DashboardPatientRoute
    }
    '/dashboard/patient/profile': {
      id: '/dashboard/patient/profile'
      path: '/profile'
      fullPath: '/dashboard/patient/profile'
      preLoaderRoute: typeof DashboardPatientProfileRouteImport
      parentRoute: typeof DashboardPatientRoute
    }
    '/dashboard/patient/prescriptions': {
      id: '/dashboard/patient/prescriptions'
      path: '/prescriptions'
      fullPath: '/dashboard/patient/prescriptions'
      preLoaderRoute: typeof DashboardPatientPrescriptionsRouteImport
      parentRoute: typeof DashboardPatientRoute
    }
    '/dashboard/patient/orders': {
      id: '/dashboard/patient/orders'
      path: '/orders'
      fullPath: '/dashboard/patient/orders'
      preLoaderRoute: typeof DashboardPatientOrdersRouteImport
      parentRoute: typeof DashboardPatientRoute
    }
    '/dashboard/patient/book-appointment': {
      id: '/dashboard/patient/book-appointment'
      path: '/book-appointment'
      fullPath: '/dashboard/patient/book-appointment'
      preLoaderRoute: typeof DashboardPatientBookAppointmentRouteImport
      parentRoute: typeof DashboardPatientRoute
    }
    '/dashboard/patient/appointments': {
      id: '/dashboard/patient/appointments'
      path: '/appointments'
      fullPath: '/dashboard/patient/appointments'
      preLoaderRoute: typeof DashboardPatientAppointmentsRouteImport
      parentRoute: typeof DashboardPatientRoute
    }
    '/dashboard/doctor/settings': {
      id: '/dashboard/doctor/settings'
      path: '/settings'
      fullPath: '/dashboard/doctor/settings'
      preLoaderRoute: typeof DashboardDoctorSettingsRouteImport
      parentRoute: typeof DashboardDoctorRoute
    }
    '/dashboard/doctor/profile': {
      id: '/dashboard/doctor/profile'
      path: '/profile'
      fullPath: '/dashboard/doctor/profile'
      preLoaderRoute: typeof DashboardDoctorProfileRouteImport
      parentRoute: typeof DashboardDoctorRoute
    }
    '/dashboard/doctor/prescriptions': {
      id: '/dashboard/doctor/prescriptions'
      path: '/prescriptions'
      fullPath: '/dashboard/doctor/prescriptions'
      preLoaderRoute: typeof DashboardDoctorPrescriptionsRouteImport
      parentRoute: typeof DashboardDoctorRoute
    }
    '/dashboard/doctor/availability': {
      id: '/dashboard/doctor/availability'
      path: '/availability'
      fullPath: '/dashboard/doctor/availability'
      preLoaderRoute: typeof DashboardDoctorAvailabilityRouteImport
      parentRoute: typeof DashboardDoctorRoute
    }
    '/dashboard/doctor/appointments': {
      id: '/dashboard/doctor/appointments'
      path: '/appointments'
      fullPath: '/dashboard/doctor/appointments'
      preLoaderRoute: typeof DashboardDoctorAppointmentsRouteImport
      parentRoute: typeof DashboardDoctorRoute
    }
    '/dashboard/admin/users': {
      id: '/dashboard/admin/users'
      path: '/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof DashboardAdminUsersRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/settings': {
      id: '/dashboard/admin/settings'
      path: '/settings'
      fullPath: '/dashboard/admin/settings'
      preLoaderRoute: typeof DashboardAdminSettingsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/pharmacist/profile/': {
      id: '/dashboard/pharmacist/profile/'
      path: '/'
      fullPath: '/dashboard/pharmacist/profile/'
      preLoaderRoute: typeof DashboardPharmacistProfileIndexRouteImport
      parentRoute: typeof DashboardPharmacistProfileRoute
    }
    '/dashboard/pharmacist/orders/': {
      id: '/dashboard/pharmacist/orders/'
      path: '/'
      fullPath: '/dashboard/pharmacist/orders/'
      preLoaderRoute: typeof DashboardPharmacistOrdersIndexRouteImport
      parentRoute: typeof DashboardPharmacistOrdersRoute
    }
    '/dashboard/patient/profile/': {
      id: '/dashboard/patient/profile/'
      path: '/'
      fullPath: '/dashboard/patient/profile/'
      preLoaderRoute: typeof DashboardPatientProfileIndexRouteImport
      parentRoute: typeof DashboardPatientProfileRoute
    }
    '/dashboard/patient/prescriptions/': {
      id: '/dashboard/patient/prescriptions/'
      path: '/'
      fullPath: '/dashboard/patient/prescriptions/'
      preLoaderRoute: typeof DashboardPatientPrescriptionsIndexRouteImport
      parentRoute: typeof DashboardPatientPrescriptionsRoute
    }
    '/dashboard/patient/orders/': {
      id: '/dashboard/patient/orders/'
      path: '/'
      fullPath: '/dashboard/patient/orders/'
      preLoaderRoute: typeof DashboardPatientOrdersIndexRouteImport
      parentRoute: typeof DashboardPatientOrdersRoute
    }
    '/dashboard/doctor/profile/': {
      id: '/dashboard/doctor/profile/'
      path: '/'
      fullPath: '/dashboard/doctor/profile/'
      preLoaderRoute: typeof DashboardDoctorProfileIndexRouteImport
      parentRoute: typeof DashboardDoctorProfileRoute
    }
    '/dashboard/doctor/prescriptions/': {
      id: '/dashboard/doctor/prescriptions/'
      path: '/'
      fullPath: '/dashboard/doctor/prescriptions/'
      preLoaderRoute: typeof DashboardDoctorPrescriptionsIndexRouteImport
      parentRoute: typeof DashboardDoctorPrescriptionsRoute
    }
    '/dashboard/doctor/appointments/': {
      id: '/dashboard/doctor/appointments/'
      path: '/'
      fullPath: '/dashboard/doctor/appointments/'
      preLoaderRoute: typeof DashboardDoctorAppointmentsIndexRouteImport
      parentRoute: typeof DashboardDoctorAppointmentsRoute
    }
    '/dashboard/pharmacist/profile/edit': {
      id: '/dashboard/pharmacist/profile/edit'
      path: '/edit'
      fullPath: '/dashboard/pharmacist/profile/edit'
      preLoaderRoute: typeof DashboardPharmacistProfileEditRouteImport
      parentRoute: typeof DashboardPharmacistProfileRoute
    }
    '/dashboard/pharmacist/profile/create': {
      id: '/dashboard/pharmacist/profile/create'
      path: '/create'
      fullPath: '/dashboard/pharmacist/profile/create'
      preLoaderRoute: typeof DashboardPharmacistProfileCreateRouteImport
      parentRoute: typeof DashboardPharmacistProfileRoute
    }
    '/dashboard/pharmacist/orders/$orderId': {
      id: '/dashboard/pharmacist/orders/$orderId'
      path: '/$orderId'
      fullPath: '/dashboard/pharmacist/orders/$orderId'
      preLoaderRoute: typeof DashboardPharmacistOrdersOrderIdRouteImport
      parentRoute: typeof DashboardPharmacistOrdersRoute
    }
    '/dashboard/patient/profile/edit': {
      id: '/dashboard/patient/profile/edit'
      path: '/edit'
      fullPath: '/dashboard/patient/profile/edit'
      preLoaderRoute: typeof DashboardPatientProfileEditRouteImport
      parentRoute: typeof DashboardPatientProfileRoute
    }
    '/dashboard/patient/profile/create': {
      id: '/dashboard/patient/profile/create'
      path: '/create'
      fullPath: '/dashboard/patient/profile/create'
      preLoaderRoute: typeof DashboardPatientProfileCreateRouteImport
      parentRoute: typeof DashboardPatientProfileRoute
    }
    '/dashboard/patient/prescriptions/$prescriptionId': {
      id: '/dashboard/patient/prescriptions/$prescriptionId'
      path: '/$prescriptionId'
      fullPath: '/dashboard/patient/prescriptions/$prescriptionId'
      preLoaderRoute: typeof DashboardPatientPrescriptionsPrescriptionIdRouteImport
      parentRoute: typeof DashboardPatientPrescriptionsRoute
    }
    '/dashboard/patient/orders/new': {
      id: '/dashboard/patient/orders/new'
      path: '/new'
      fullPath: '/dashboard/patient/orders/new'
      preLoaderRoute: typeof DashboardPatientOrdersNewRouteImport
      parentRoute: typeof DashboardPatientOrdersRoute
    }
    '/dashboard/patient/orders/$orderId': {
      id: '/dashboard/patient/orders/$orderId'
      path: '/$orderId'
      fullPath: '/dashboard/patient/orders/$orderId'
      preLoaderRoute: typeof DashboardPatientOrdersOrderIdRouteImport
      parentRoute: typeof DashboardPatientOrdersRoute
    }
    '/dashboard/doctor/profile/edit': {
      id: '/dashboard/doctor/profile/edit'
      path: '/edit'
      fullPath: '/dashboard/doctor/profile/edit'
      preLoaderRoute: typeof DashboardDoctorProfileEditRouteImport
      parentRoute: typeof DashboardDoctorProfileRoute
    }
    '/dashboard/doctor/profile/create': {
      id: '/dashboard/doctor/profile/create'
      path: '/create'
      fullPath: '/dashboard/doctor/profile/create'
      preLoaderRoute: typeof DashboardDoctorProfileCreateRouteImport
      parentRoute: typeof DashboardDoctorProfileRoute
    }
    '/dashboard/doctor/prescriptions/new': {
      id: '/dashboard/doctor/prescriptions/new'
      path: '/new'
      fullPath: '/dashboard/doctor/prescriptions/new'
      preLoaderRoute: typeof DashboardDoctorPrescriptionsNewRouteImport
      parentRoute: typeof DashboardDoctorPrescriptionsRoute
    }
    '/dashboard/doctor/prescriptions/$prescriptionId': {
      id: '/dashboard/doctor/prescriptions/$prescriptionId'
      path: '/$prescriptionId'
      fullPath: '/dashboard/doctor/prescriptions/$prescriptionId'
      preLoaderRoute: typeof DashboardDoctorPrescriptionsPrescriptionIdRouteImport
      parentRoute: typeof DashboardDoctorPrescriptionsRoute
    }
    '/dashboard/doctor/appointments/$appointmentId': {
      id: '/dashboard/doctor/appointments/$appointmentId'
      path: '/$appointmentId'
      fullPath: '/dashboard/doctor/appointments/$appointmentId'
      preLoaderRoute: typeof DashboardDoctorAppointmentsAppointmentIdRouteImport
      parentRoute: typeof DashboardDoctorAppointmentsRoute
    }
  }
}

interface DashboardAdminRouteChildren {
  DashboardAdminSettingsRoute: typeof DashboardAdminSettingsRoute
  DashboardAdminUsersRoute: typeof DashboardAdminUsersRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminSettingsRoute: DashboardAdminSettingsRoute,
  DashboardAdminUsersRoute: DashboardAdminUsersRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardDoctorAppointmentsRouteChildren {
  DashboardDoctorAppointmentsAppointmentIdRoute: typeof DashboardDoctorAppointmentsAppointmentIdRoute
  DashboardDoctorAppointmentsIndexRoute: typeof DashboardDoctorAppointmentsIndexRoute
}

const DashboardDoctorAppointmentsRouteChildren: DashboardDoctorAppointmentsRouteChildren =
  {
    DashboardDoctorAppointmentsAppointmentIdRoute:
      DashboardDoctorAppointmentsAppointmentIdRoute,
    DashboardDoctorAppointmentsIndexRoute:
      DashboardDoctorAppointmentsIndexRoute,
  }

const DashboardDoctorAppointmentsRouteWithChildren =
  DashboardDoctorAppointmentsRoute._addFileChildren(
    DashboardDoctorAppointmentsRouteChildren,
  )

interface DashboardDoctorPrescriptionsRouteChildren {
  DashboardDoctorPrescriptionsPrescriptionIdRoute: typeof DashboardDoctorPrescriptionsPrescriptionIdRoute
  DashboardDoctorPrescriptionsNewRoute: typeof DashboardDoctorPrescriptionsNewRoute
  DashboardDoctorPrescriptionsIndexRoute: typeof DashboardDoctorPrescriptionsIndexRoute
}

const DashboardDoctorPrescriptionsRouteChildren: DashboardDoctorPrescriptionsRouteChildren =
  {
    DashboardDoctorPrescriptionsPrescriptionIdRoute:
      DashboardDoctorPrescriptionsPrescriptionIdRoute,
    DashboardDoctorPrescriptionsNewRoute: DashboardDoctorPrescriptionsNewRoute,
    DashboardDoctorPrescriptionsIndexRoute:
      DashboardDoctorPrescriptionsIndexRoute,
  }

const DashboardDoctorPrescriptionsRouteWithChildren =
  DashboardDoctorPrescriptionsRoute._addFileChildren(
    DashboardDoctorPrescriptionsRouteChildren,
  )

interface DashboardDoctorProfileRouteChildren {
  DashboardDoctorProfileCreateRoute: typeof DashboardDoctorProfileCreateRoute
  DashboardDoctorProfileEditRoute: typeof DashboardDoctorProfileEditRoute
  DashboardDoctorProfileIndexRoute: typeof DashboardDoctorProfileIndexRoute
}

const DashboardDoctorProfileRouteChildren: DashboardDoctorProfileRouteChildren =
  {
    DashboardDoctorProfileCreateRoute: DashboardDoctorProfileCreateRoute,
    DashboardDoctorProfileEditRoute: DashboardDoctorProfileEditRoute,
    DashboardDoctorProfileIndexRoute: DashboardDoctorProfileIndexRoute,
  }

const DashboardDoctorProfileRouteWithChildren =
  DashboardDoctorProfileRoute._addFileChildren(
    DashboardDoctorProfileRouteChildren,
  )

interface DashboardDoctorRouteChildren {
  DashboardDoctorAppointmentsRoute: typeof DashboardDoctorAppointmentsRouteWithChildren
  DashboardDoctorAvailabilityRoute: typeof DashboardDoctorAvailabilityRoute
  DashboardDoctorPrescriptionsRoute: typeof DashboardDoctorPrescriptionsRouteWithChildren
  DashboardDoctorProfileRoute: typeof DashboardDoctorProfileRouteWithChildren
  DashboardDoctorSettingsRoute: typeof DashboardDoctorSettingsRoute
  DashboardDoctorIndexRoute: typeof DashboardDoctorIndexRoute
}

const DashboardDoctorRouteChildren: DashboardDoctorRouteChildren = {
  DashboardDoctorAppointmentsRoute:
    DashboardDoctorAppointmentsRouteWithChildren,
  DashboardDoctorAvailabilityRoute: DashboardDoctorAvailabilityRoute,
  DashboardDoctorPrescriptionsRoute:
    DashboardDoctorPrescriptionsRouteWithChildren,
  DashboardDoctorProfileRoute: DashboardDoctorProfileRouteWithChildren,
  DashboardDoctorSettingsRoute: DashboardDoctorSettingsRoute,
  DashboardDoctorIndexRoute: DashboardDoctorIndexRoute,
}

const DashboardDoctorRouteWithChildren = DashboardDoctorRoute._addFileChildren(
  DashboardDoctorRouteChildren,
)

interface DashboardPatientOrdersRouteChildren {
  DashboardPatientOrdersOrderIdRoute: typeof DashboardPatientOrdersOrderIdRoute
  DashboardPatientOrdersNewRoute: typeof DashboardPatientOrdersNewRoute
  DashboardPatientOrdersIndexRoute: typeof DashboardPatientOrdersIndexRoute
}

const DashboardPatientOrdersRouteChildren: DashboardPatientOrdersRouteChildren =
  {
    DashboardPatientOrdersOrderIdRoute: DashboardPatientOrdersOrderIdRoute,
    DashboardPatientOrdersNewRoute: DashboardPatientOrdersNewRoute,
    DashboardPatientOrdersIndexRoute: DashboardPatientOrdersIndexRoute,
  }

const DashboardPatientOrdersRouteWithChildren =
  DashboardPatientOrdersRoute._addFileChildren(
    DashboardPatientOrdersRouteChildren,
  )

interface DashboardPatientPrescriptionsRouteChildren {
  DashboardPatientPrescriptionsPrescriptionIdRoute: typeof DashboardPatientPrescriptionsPrescriptionIdRoute
  DashboardPatientPrescriptionsIndexRoute: typeof DashboardPatientPrescriptionsIndexRoute
}

const DashboardPatientPrescriptionsRouteChildren: DashboardPatientPrescriptionsRouteChildren =
  {
    DashboardPatientPrescriptionsPrescriptionIdRoute:
      DashboardPatientPrescriptionsPrescriptionIdRoute,
    DashboardPatientPrescriptionsIndexRoute:
      DashboardPatientPrescriptionsIndexRoute,
  }

const DashboardPatientPrescriptionsRouteWithChildren =
  DashboardPatientPrescriptionsRoute._addFileChildren(
    DashboardPatientPrescriptionsRouteChildren,
  )

interface DashboardPatientProfileRouteChildren {
  DashboardPatientProfileCreateRoute: typeof DashboardPatientProfileCreateRoute
  DashboardPatientProfileEditRoute: typeof DashboardPatientProfileEditRoute
  DashboardPatientProfileIndexRoute: typeof DashboardPatientProfileIndexRoute
}

const DashboardPatientProfileRouteChildren: DashboardPatientProfileRouteChildren =
  {
    DashboardPatientProfileCreateRoute: DashboardPatientProfileCreateRoute,
    DashboardPatientProfileEditRoute: DashboardPatientProfileEditRoute,
    DashboardPatientProfileIndexRoute: DashboardPatientProfileIndexRoute,
  }

const DashboardPatientProfileRouteWithChildren =
  DashboardPatientProfileRoute._addFileChildren(
    DashboardPatientProfileRouteChildren,
  )

interface DashboardPatientRouteChildren {
  DashboardPatientAppointmentsRoute: typeof DashboardPatientAppointmentsRoute
  DashboardPatientBookAppointmentRoute: typeof DashboardPatientBookAppointmentRoute
  DashboardPatientOrdersRoute: typeof DashboardPatientOrdersRouteWithChildren
  DashboardPatientPrescriptionsRoute: typeof DashboardPatientPrescriptionsRouteWithChildren
  DashboardPatientProfileRoute: typeof DashboardPatientProfileRouteWithChildren
  DashboardPatientSettingsRoute: typeof DashboardPatientSettingsRoute
  DashboardPatientIndexRoute: typeof DashboardPatientIndexRoute
}

const DashboardPatientRouteChildren: DashboardPatientRouteChildren = {
  DashboardPatientAppointmentsRoute: DashboardPatientAppointmentsRoute,
  DashboardPatientBookAppointmentRoute: DashboardPatientBookAppointmentRoute,
  DashboardPatientOrdersRoute: DashboardPatientOrdersRouteWithChildren,
  DashboardPatientPrescriptionsRoute:
    DashboardPatientPrescriptionsRouteWithChildren,
  DashboardPatientProfileRoute: DashboardPatientProfileRouteWithChildren,
  DashboardPatientSettingsRoute: DashboardPatientSettingsRoute,
  DashboardPatientIndexRoute: DashboardPatientIndexRoute,
}

const DashboardPatientRouteWithChildren =
  DashboardPatientRoute._addFileChildren(DashboardPatientRouteChildren)

interface DashboardPharmacistOrdersRouteChildren {
  DashboardPharmacistOrdersOrderIdRoute: typeof DashboardPharmacistOrdersOrderIdRoute
  DashboardPharmacistOrdersIndexRoute: typeof DashboardPharmacistOrdersIndexRoute
}

const DashboardPharmacistOrdersRouteChildren: DashboardPharmacistOrdersRouteChildren =
  {
    DashboardPharmacistOrdersOrderIdRoute:
      DashboardPharmacistOrdersOrderIdRoute,
    DashboardPharmacistOrdersIndexRoute: DashboardPharmacistOrdersIndexRoute,
  }

const DashboardPharmacistOrdersRouteWithChildren =
  DashboardPharmacistOrdersRoute._addFileChildren(
    DashboardPharmacistOrdersRouteChildren,
  )

interface DashboardPharmacistProfileRouteChildren {
  DashboardPharmacistProfileCreateRoute: typeof DashboardPharmacistProfileCreateRoute
  DashboardPharmacistProfileEditRoute: typeof DashboardPharmacistProfileEditRoute
  DashboardPharmacistProfileIndexRoute: typeof DashboardPharmacistProfileIndexRoute
}

const DashboardPharmacistProfileRouteChildren: DashboardPharmacistProfileRouteChildren =
  {
    DashboardPharmacistProfileCreateRoute:
      DashboardPharmacistProfileCreateRoute,
    DashboardPharmacistProfileEditRoute: DashboardPharmacistProfileEditRoute,
    DashboardPharmacistProfileIndexRoute: DashboardPharmacistProfileIndexRoute,
  }

const DashboardPharmacistProfileRouteWithChildren =
  DashboardPharmacistProfileRoute._addFileChildren(
    DashboardPharmacistProfileRouteChildren,
  )

interface DashboardPharmacistRouteChildren {
  DashboardPharmacistInventoryRoute: typeof DashboardPharmacistInventoryRoute
  DashboardPharmacistMedicineRoute: typeof DashboardPharmacistMedicineRoute
  DashboardPharmacistOrdersRoute: typeof DashboardPharmacistOrdersRouteWithChildren
  DashboardPharmacistProfileRoute: typeof DashboardPharmacistProfileRouteWithChildren
  DashboardPharmacistSettingsRoute: typeof DashboardPharmacistSettingsRoute
  DashboardPharmacistIndexRoute: typeof DashboardPharmacistIndexRoute
}

const DashboardPharmacistRouteChildren: DashboardPharmacistRouteChildren = {
  DashboardPharmacistInventoryRoute: DashboardPharmacistInventoryRoute,
  DashboardPharmacistMedicineRoute: DashboardPharmacistMedicineRoute,
  DashboardPharmacistOrdersRoute: DashboardPharmacistOrdersRouteWithChildren,
  DashboardPharmacistProfileRoute: DashboardPharmacistProfileRouteWithChildren,
  DashboardPharmacistSettingsRoute: DashboardPharmacistSettingsRoute,
  DashboardPharmacistIndexRoute: DashboardPharmacistIndexRoute,
}

const DashboardPharmacistRouteWithChildren =
  DashboardPharmacistRoute._addFileChildren(DashboardPharmacistRouteChildren)

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardDoctorRoute: typeof DashboardDoctorRouteWithChildren
  DashboardPatientRoute: typeof DashboardPatientRouteWithChildren
  DashboardPharmacistRoute: typeof DashboardPharmacistRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardDoctorRoute: DashboardDoctorRouteWithChildren,
  DashboardPatientRoute: DashboardPatientRouteWithChildren,
  DashboardPharmacistRoute: DashboardPharmacistRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
